# Generated by Django 5.0.2 on 2024-04-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('servico_escolhido', models.CharField(max_length=100)),
                ('horario_escolhido', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Serviços Agendado',
            },
        ),
        migrations.CreateModel(
            name='AgendarServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='thumb-site')),
            ],
            options={
                'verbose_name': 'Configuração de Agendar Servico Ajuste',
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('fundo_imagem', models.ImageField(upload_to='thumb-site')),
                ('link_whatsaap', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Configuração de Contato Ajuste',
            },
        ),
        migrations.CreateModel(
            name='HorarioAjustes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horarios', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Configuração de Horários Ajuste',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil_imagem', models.ImageField(upload_to='thumb-site')),
                ('nome_perfil', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=1000)),
                ('logo_site', models.ImageField(upload_to='thumb-site')),
            ],
            options={
                'verbose_name': 'Configuração de Perfil Ajuste',
            },
        ),
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='thumb-site')),
                ('servico', models.CharField(max_length=100)),
                ('preco', models.FloatField()),
            ],
            options={
                'verbose_name': 'Configuração de Servico Ajuste',
            },
        ),
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('render_profile', models.ImageField(upload_to='thumb-site')),
                ('descricao', models.TextField(max_length=800)),
                ('profissao', models.ManyToManyField(to='app.profissao')),
            ],
            options={
                'verbose_name': 'Configuração Sobre mim Ajuste',
            },
        ),
    ]
